import { StaffRecord } from "@/types/staff";

export const mockStaffMembers: StaffRecord[] = [
  {
    id: "AE-DRV-4791",
    code: "AE-DRV-4791",
    name: "Liam Vance",
    phone: "+1 (555) 301-4490",
    email: "liam.vance@sarana.bistro",
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop",
    role: "delivery",
    roleLabel: "Senior Courier",
    status: "on_delivery",
    statusLabel: "ON DELIVERY",
    vehicleType: "motorbike",
    vehicleLabel: "Yamaha NMAX #2",
    vehiclePlate: "PP-1AB-4892",
    activeOrderId: "#1024",
    activeCustomerName: "John Smith",
    activeDestination: "742 Evergreen Terr (0.8 mi)",
    deliveriesToday: 14,
    avgDeliveryMinutes: 18,
    codCashCollected: 34.5,
    tipsToday: 14.5,
    shiftStartTime: "11:00 AM",
    rating: 4.9,
    joinedDate: "Mar 2023",
  },
  {
    id: "AE-DRV-4798",
    code: "AE-DRV-4798",
    name: "David Chen",
    phone: "+1 (555) 891-2240",
    email: "david.chen@sarana.bistro",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop",
    role: "delivery",
    roleLabel: "Express Rider",
    status: "on_delivery",
    statusLabel: "ON DELIVERY",
    vehicleType: "motorbike",
    vehicleLabel: "Honda Wave #1",
    vehiclePlate: "PP-2CD-9912",
    activeOrderId: "#1027",
    activeCustomerName: "Elena Vance",
    activeDestination: "12 Riverside Prom (2.1 mi)",
    deliveriesToday: 11,
    avgDeliveryMinutes: 21,
    codCashCollected: 62.0,
    tipsToday: 18.0,
    shiftStartTime: "12:30 PM",
    rating: 4.8,
    joinedDate: "Aug 2023",
  },
  {
    id: "AE-DRV-4802",
    code: "AE-DRV-4802",
    name: "Sokha Seng",
    phone: "+1 (555) 773-4019",
    email: "sokha.seng@sarana.bistro",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop",
    role: "delivery",
    roleLabel: "Eco Courier",
    status: "available",
    statusLabel: "ONLINE",
    vehicleType: "e_scooter",
    vehicleLabel: "E-Scooter Pro #4",
    vehiclePlate: "ECO-S-04",
    deliveriesToday: 9,
    avgDeliveryMinutes: 15,
    codCashCollected: 69.0,
    tipsToday: 22.5,
    shiftStartTime: "01:00 PM",
    rating: 4.95,
    joinedDate: "Jan 2024",
  },
  {
    id: "AE-DRV-4815",
    code: "AE-DRV-4815",
    name: "Borey Roth",
    phone: "+1 (555) 902-8812",
    email: "borey.roth@sarana.bistro",
    avatarUrl:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop",
    role: "delivery",
    roleLabel: "Express Rider",
    status: "available",
    statusLabel: "ONLINE",
    vehicleType: "motorbike",
    vehicleLabel: "Honda Click #7",
    vehiclePlate: "PP-1XY-1092",
    deliveriesToday: 8,
    avgDeliveryMinutes: 16,
    codCashCollected: 0.0,
    tipsToday: 8.0,
    shiftStartTime: "10:00 AM",
    rating: 4.7,
    joinedDate: "Nov 2023",
  },
  {
    id: "AE-DRV-4820",
    code: "AE-DRV-4820",
    name: "Alex Turner",
    phone: "+1 (555) 319-0012",
    email: "alex.t@sarana.bistro",
    avatarUrl:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop",
    role: "delivery",
    roleLabel: "Backup Courier",
    status: "logout",
    statusLabel: "LOGOUT",
    vehicleType: "bicycle",
    vehicleLabel: "Cargo Bike #1",
    deliveriesToday: 0,
    avgDeliveryMinutes: 0,
    codCashCollected: 0.0,
    tipsToday: 0.0,
    rating: 4.6,
    joinedDate: "May 2024",
  },
];
