import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./layouts/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#a43700",
          foreground: "#ffffff",
          container: "#c64e1b",
          fixed: "#ffdbcf",
          "fixed-dim": "#ffb59a",
        },
        "on-primary": "#ffffff",
        "on-primary-fixed": "#380d00",
        "on-primary-fixed-variant": "#812900",
        "on-primary-container": "#fffbff",
        "primary-container": "#c64e1b",
        "primary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#ffb59a",
        secondary: {
          DEFAULT: "#8f4e00",
          foreground: "#ffffff",
          container: "#fea047",
          fixed: "#ffdcc2",
          "fixed-dim": "#ffb77a",
        },
        "on-secondary": "#ffffff",
        "secondary-container": "#fea047",
        "on-secondary-container": "#6d3a00",
        "secondary-fixed": "#ffdcc2",
        "on-secondary-fixed": "#2e1500",
        "on-secondary-fixed-variant": "#6d3a00",
        "secondary-fixed-dim": "#ffb77a",
        tertiary: {
          DEFAULT: "#605b58",
          container: "#797370",
          fixed: "#e9e1dd",
          "fixed-dim": "#ccc5c1",
        },
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "tertiary-container": "#797370",
        "tertiary-fixed": "#e9e1dd",
        "tertiary-fixed-dim": "#ccc5c1",
        "on-tertiary-fixed": "#1e1b19",
        "on-tertiary-fixed-variant": "#4a4643",
        surface: {
          DEFAULT: "#fcf9f3",
          bright: "#fcf9f3",
          dim: "#dcdad4",
          variant: "#e5e2dc",
          tint: "#a83902",
          container: "#f0eee8",
          "container-lowest": "#ffffff",
          "container-low": "#f6f3ed",
          "container-high": "#ebe8e2",
          "container-highest": "#e5e2dc",
        },
        "surface-bright": "#fcf9f3",
        "surface-dim": "#dcdad4",
        "surface-variant": "#e5e2dc",
        "surface-tint": "#a83902",
        "surface-container": "#f0eee8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ed",
        "surface-container-high": "#ebe8e2",
        "surface-container-highest": "#e5e2dc",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#58423a",
        "inverse-surface": "#31312d",
        "inverse-on-surface": "#f3f0ea",
        "inverse-primary": "#ffb59a",
        outline: "#8c7168",
        "outline-variant": "#e0c0b5",
        destructive: {
          DEFAULT: "#ba1a1a",
          foreground: "#ffffff",
        },
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        muted: {
          DEFAULT: "#f0eee8",
          foreground: "#58423a",
        },
        accent: {
          DEFAULT: "#ffdcc2",
          foreground: "#2e1500",
        },
        card: {
          DEFAULT: "#ffffff",
          foreground: "#1c1c18",
        },
      },
      borderRadius: {
        lg: "0.5rem",
        md: "0.375rem",
        sm: "0.25rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "2.5rem",
        "card-inner-padding": "1rem",
        "screen-edge-padding": "1.25rem",
        "sticky-bottom-offset": "5.5rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;

